insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Jaymie', 'Shottin', '7829843355', '97 Fisk Road', '237', null, 'Guanxi');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Joshuah', 'MacClinton', '2918466385', '713 Golf Way', '702', null, 'Kendaruan');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Waite', 'Deniskevich', '1863773979', '92 Forest Hill', '63654', null, 'Águas Vermelhas');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Marji', 'Spadotto', '5858762793', '56 Scott Parkway', '051', null, 'Koška');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Brad', 'Davis', '7328533077', '1 Merry Crossing', '87', null, 'Kafr Mandā');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Sherman', 'Troth', '8508917846', '0265 Bobwhite Street', '813', null, 'Balatun');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Ximenes', 'Headingham', '1429218920', '5424 Oxford Point', '0', null, 'Umuquena');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Cate', 'Marrison', '8672712659', '172 Bay Circle', '95', null, 'Huxi');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Farrand', 'Dedham', '3796972866', '793 Shopko Pass', '46', null, 'Putre');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Mabel', 'Jerome', '2751344076', '900 Northland Avenue', '5', null, 'Tagta');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Agnese', 'Tourner', '3547626777', '834 Vermont Court', '06', null, 'Tatuí');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Jyoti', 'Kobsch', '5072367498', '43449 Elgar Pass', '087', null, 'João Pinheiro');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Abbie', 'Rosel', '8804477955', '958 Lake View Alley', '85', null, 'Natal');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Jamal', 'Skatcher', '5715776681', '4432 Prentice Way', '452', null, 'Tarxien');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Dynah', 'Harker', '6146781604', '776 Schmedeman Court', '583', 'Ohio', 'Columbus');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Normy', 'Kinig', '1001947957', '1152 Stephen Drive', '1858', null, 'Leones');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Abner', 'Baron', '7676342556', '5 Butterfield Plaza', '0', null, 'Ning’an');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Simon', 'Succamore', '7048188503', '9 Rockefeller Way', '1', 'North Carolina', 'Charlotte');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Gladi', 'Schanke', '6744315665', '3 Mendota Junction', '4960', null, 'Gunan');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Rawley', 'Pennrington', '6388621019', '061 Ronald Regan Alley', '57', null, 'Wasior');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Ann', 'Sweedy', '7385845798', '12638 Comanche Street', '97316', null, 'Leiwang');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Rorke', 'Tures', '7795490884', '34 Grover Lane', '24929', null, 'Elassóna');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Nicko', 'Roddy', '6261727687', '30 Monica Hill', '90584', null, 'Willemstad');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Arlana', 'Burchnall', '4094087371', '952 Riverside Park', '04308', null, 'Provatás');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Stanislaw', 'Oluwatoyin', '6024061715', '0403 Ilene Street', '74240', 'Arizona', 'Phoenix');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Conny', 'Phil', '4978183238', '9914 Kennedy Trail', '34', null, 'Xishan');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Brody', 'Cash', '3601033560', '827 Lukken Junction', '82602', null, 'Velký Újezd');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Janean', 'Mordaunt', '6962066694', '9623 Hoepker Alley', '297', null, 'Pangradin Satu');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Tana', 'Hazart', '2068169707', '255 Elgar Terrace', '84249', null, 'Nueva Requena');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Benyamin', 'Maciocia', '7511035590', '81 Bartelt Terrace', '7052', null, 'Vydreno');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Koenraad', 'Leale', '6787008391', '6748 Ryan Plaza', '67824', null, 'Saguday');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Tasia', 'Casiero', '7575325791', '33692 Roth Point', '88', null, 'Caotang');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Guss', 'Kingzet', '3974875581', '297 Rockefeller Drive', '12', null, 'Tajinan');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Allyson', 'Toyer', '2819172211', '9 Stone Corner Circle', '0361', 'Texas', 'Houston');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Ferne', 'Ferrea', '3343256722', '82161 Debra Junction', '577', 'Alabama', 'Montgomery');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Rabbi', 'Norcliff', '7186038784', '40 Muir Street', '901', null, 'Hewa');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Clari', 'Feilden', '3616941878', '63144 Fairview Hill', '6246', null, 'Cikananga');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Joleen', 'Montrose', '6321602471', '30 Nancy Pass', '50', null, 'Andrijevica');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Alick', 'Flatt', '6684136148', '742 Pawling Circle', '840', null, 'Staraya Ladoga');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Emogene', 'Fritschel', '9304220242', '80752 Summit Road', '831', null, 'Chenqiao');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Selia', 'Blount', '4595866025', '757 Hovde Parkway', '52', 'Aveiro', 'Outeiro');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Noble', 'Toynbee', '5703114656', '29 Anderson Court', '34', null, 'Hadano');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Garfield', 'Trembley', '8804554670', '0940 Petterle Avenue', '93', null, 'Jalal-Abad');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Zollie', 'Curless', '9029783681', '610 Kings Circle', '13', null, 'Nyinqug');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Lucas', 'Peatheyjohns', '5328345614', '93709 Grover Crossing', '5900', null, 'Yangsan');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Clo', 'Bladen', '6564148279', '13 Pearson Court', '31', null, 'Samacá');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Gilbert', 'Barrett', '1076662594', '9512 Westerfield Center', '048', null, 'Filótion');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Akim', 'Doumer', '6555313367', '628 Sutherland Circle', '74', null, 'Atsipópoulon');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Bamby', 'Durrance', '5056126753', '244 Badeau Point', '6533', null, 'Xianghu');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Daniel', 'Losbie', '1271436582', '9017 Briar Crest Junction', '146', null, 'Bassar');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Mindy', 'Gellately', '1657874557', '35207 Nobel Park', '2319', 'Basse-Normandie', 'Caen');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Rosabel', 'Astin', '4823836453', '34365 Pearson Road', '473', null, 'Aco');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Bart', 'Giocannoni', '8363654206', '55072 Rockefeller Drive', '00071', null, 'Krasnyy Oktyabr’');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Frannie', 'McMearty', '2944807031', '07616 Dorton Plaza', '65188', null, 'Joševa');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Clerissa', 'Newbery', '9051072558', '10 Shelley Crossing', '468', 'Champagne-Ardenne', 'Reims');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Tremayne', 'Cloney', '8317014430', '3985 Summit Hill', '114', null, 'Daqin Tal');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Marketa', 'Loram', '7271736677', '5 Buena Vista Trail', '404', null, 'Annau');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Gerald', 'O''Caine', '7431942928', '5 Anthes Hill', '6', null, 'Doushan');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Kermit', 'Danis', '5058788231', '2 Gateway Place', '9597', null, 'Yuanbao');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Keely', 'Youll', '8996365975', '6 Bayside Circle', '7065', null, 'Almaguer');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Anson', 'Rounce', '2006088904', '9609 Oakridge Terrace', '203', null, 'Zruč nad Sázavou');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Cornelius', 'Ionnidis', '2576652399', '26 Buhler Plaza', '741', null, 'Cogon');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Ofelia', 'Grindlay', '5972577171', '2991 Buell Center', '99207', null, 'Lewolen');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Katy', 'Hanalan', '9539427142', '9483 Lighthouse Bay Trail', '380', null, 'Sāqayn');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Ethelin', 'de Savery', '3236116383', '48 Upham Avenue', '765', null, 'Šabac');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Maryrose', 'Pawlaczyk', '1974476036', '18 Prentice Junction', '315', null, 'Qamdo');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Kurt', 'Hannum', '2117264016', '86 North Alley', '37', null, 'Houxixi');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Leandra', 'De Blasio', '3345791448', '23313 Division Parkway', '1', null, 'Segoro');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Jermayne', 'Beauvais', '8957993394', '028 Independence Circle', '1971', null, 'Słupno');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Pepito', 'Radeliffe', '9666994672', '5019 Helena Court', '096', null, 'Sali');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Allene', 'Caudelier', '8779983394', '65438 Monument Place', '22', null, 'Palmito');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Claire', 'Barter', '3376730839', '43 Autumn Leaf Way', '20', null, 'Jindayris');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Darn', 'Jahnke', '9454220266', '6 Green Ridge Pass', '7350', null, 'Cayambe');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Peter', 'Ginglell', '6568254629', '07 Norway Maple Center', '95543', null, 'Acharnés');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Paddie', 'Banstead', '7125595619', '08 Green Ridge Way', '6958', null, 'Itajuípe');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Merl', 'McFade', '8112022856', '734 Shelley Hill', '2', null, 'Markópoulo');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Hamlin', 'Jaume', '9755196046', '0 1st Hill', '49078', null, 'Shushicë');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Maribel', 'Bretherick', '3345918373', '7934 Becker Alley', '26650', null, 'Verblyany');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Mariejeanne', 'Gallahue', '2631319050', '27674 Mitchell Trail', '5739', null, 'Chernelytsya');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Hercules', 'Russan', '2225798929', '6 Hovde Crossing', '5', null, 'Heishan');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Solomon', 'De Courtney', '9515088735', '6 Clove Circle', '433', null, 'Padre Paraíso');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Kiele', 'Logg', '1832954608', '8 Hoepker Plaza', '50648', null, 'Ouro Branco');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Bengt', 'Holleworth', '2933148608', '609 La Follette Street', '4042', 'Viana do Castelo', 'Pousada');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Matthieu', 'Boulger', '4086690145', '8069 Tennyson Way', '96136', null, 'Kanie');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Roland', 'Fibbit', '7913981705', '811 Brickson Park Park', '12', null, 'Caitang');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Lisabeth', 'Garratty', '3049875827', '8482 Homewood Pass', '488', null, 'Wonorejo');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Lindsy', 'Nazareth', '4502704079', '28531 Steensland Crossing', '664', null, 'Talangbetutu');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Alonso', 'McIlraith', '1653145942', '4 Quincy Street', '8429', null, 'Shiqiao');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Charlotta', 'Cockshut', '3753682209', '32202 Hooker Pass', '9422', null, 'Rače');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Elsey', 'Derby', '2801007659', '14 Hovde Park', '2', null, 'Bununu Dass');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Lawry', 'Paske', '4198829607', '9746 Westerfield Junction', '705', null, 'Pefkochóri');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Leontyne', 'Jursch', '1206414794', '468 Homewood Crossing', '866', null, 'Sarimukti Kaler');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Earl', 'Geaney', '4848408958', '0907 Shopko Circle', '3736', null, 'Sysert’');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Carrissa', 'Newarte', '7304640677', '774 Tomscot Park', '57062', null, 'Prachuap Khiri Khan');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Bealle', 'Youngman', '2929483770', '01964 Gulseth Junction', '2', null, 'Cikondang');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Lannie', 'Deinhardt', '5317663856', '2 Mallard Street', '8123', null, 'Baykalovo');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Elga', 'Nuzzi', '1663450772', '00 Sauthoff Point', '123', null, 'Cevicos');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Angelika', 'Dowzell', '6538067891', '0 Barby Center', '27', 'Stockholm', 'Stockholm');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Denis', 'Mycock', '1307688247', '4 Logan Court', '4', null, 'Jām Sāhib');
insert into clientes (nombre, apellido, telefono, direccion, cp, provincia, ciudad) values ('Sianna', 'O''Rourke', '2659108463', '0 Truax Hill', '3668', null, 'Yushan');
