-- MySQL Script generated by MySQL Workbench
-- Mon Dec 11 22:11:42 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tpv
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tpv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tpv` DEFAULT CHARACTER SET latin1 ;
USE `tpv` ;

-- -----------------------------------------------------
-- Table `tpv`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpv`.`clientes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `cp` VARCHAR(45) NULL DEFAULT NULL,
  `ciudad` VARCHAR(45) NULL DEFAULT NULL,
  `provincia` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tpv`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpv`.`ventas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `clientes_id` INT(11) NOT NULL,
  `ticket` INT NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ventas_clientes_idx` (`clientes_id` ASC),
  CONSTRAINT `fk_ventas_clientes`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `tpv`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpv`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpv`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cafes` VARCHAR(45) NULL,
  `chocolates` VARCHAR(45) NULL,
  `infusiones` VARCHAR(45) NULL,
  `zumos` VARCHAR(45) NULL,
  `bolleria` VARCHAR(45) NULL,
  `bocadillos` VARCHAR(45) NULL,
  `menus` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpv`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpv`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categorias_id` INT NOT NULL,
  `cafe_corto` VARCHAR(45) NULL,
  `cafe_largo` VARCHAR(45) NULL,
  `cafe_cortado` VARCHAR(45) NULL,
  `cafe_con_leche` VARCHAR(45) NULL,
  `cafe_capuccino` VARCHAR(45) NULL,
  `cafe_carajillo` VARCHAR(45) NULL,
  `chocolate_grande` VARCHAR(45) NULL,
  `chocolate_pequeno` VARCHAR(45) NULL,
  `chocolate_suizo` VARCHAR(45) NULL,
  `te_negro` VARCHAR(45) NULL,
  `te_leche` VARCHAR(45) NULL,
  `te_chai_latte` VARCHAR(45) NULL,
  `te_menta` VARCHAR(45) NULL,
  `te_manzanilla` VARCHAR(45) NULL,
  `zumo_naranja` VARCHAR(45) NULL,
  `zumo_pina` VARCHAR(45) NULL,
  `zumo_melocoton` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `categorias_id`),
  INDEX `fk_productos_categorias1_idx` (`categorias_id` ASC),
  CONSTRAINT `fk_productos_categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `tpv`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpv`.`productos_has_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpv`.`productos_has_ventas` (
  `productos_id` INT NOT NULL,
  `ventas_id` INT NOT NULL,
  PRIMARY KEY (`productos_id`, `ventas_id`),
  INDEX `fk_productos_has_ventas_ventas1_idx` (`ventas_id` ASC),
  INDEX `fk_productos_has_ventas_productos1_idx` (`productos_id` ASC),
  CONSTRAINT `fk_productos_has_ventas_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `tpv`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_has_ventas_ventas1`
    FOREIGN KEY (`ventas_id`)
    REFERENCES `tpv`.`ventas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
