/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.hauptman.vista;

import es.hauptman.acciones.AccionesFacturas;
import es.hauptman.acciones.AccionesProductos;
import es.hauptman.acciones.AccionesVentas;
import es.hauptman.entities.Productos;
import es.hauptman.principal.FrameHome;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego
 */
public class PanelVentas extends javax.swing.JPanel {
    private FrameHome frame;
    private AccionesVentas accionesVentas;
    private AccionesFacturas accionesFacturas;
    private AccionesProductos accionesProductos;
    //FIXME
    private Productos prodSeleccionado;
    private NumberFormat currencyFormatter; 
    static double totalBruto;
    List<Productos> listaProductosVenta = new ArrayList<>();

    
    /**
     * Creates new form Ventas
     * @param frame
     */
    public PanelVentas(FrameHome frame) {
        this.frame = frame;
        initComponents();
        accionesVentas = new AccionesVentas();
        accionesFacturas = new AccionesFacturas(this);
        accionesProductos = new AccionesProductos(this);
        //FIXME
        prodSeleccionado = new Productos();
        currencyFormatter = NumberFormat.getCurrencyInstance(Locale.GERMANY);
        //Usa la clase DocumentFilter para limitar el campo de texto para recibir solo numeros enteros.
        MyIntFilter.formatInt(txtCantidad);
        
        //Muestra la fecha en la caja de texto txtFecha
        Date fecha = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd-MMM-YYYY");
        txtFecha.setText(formato.format(fecha));
        
        //Muestra la hora en la caja de texto txtHora
        Timer tiempo=new Timer(100, new PanelVentas.horas());
        tiempo.start();
    }
    
    public FrameHome getFrame() {
        return frame;
    }

    public void setFrame(FrameHome frame) {
        this.frame = frame;
    }
    
    /**
     * Método para sumar los valores del subtotal de la tabla.
     * @return int
     */
    public double getSumPrecio(){
        
        int rowCount = tablaVentas.getRowCount();
        double sum = 0;
        for(int i=0;i < rowCount;i++){
            sum=sum+Double.parseDouble(tablaVentas.getValueAt(i, 4).toString());
        }
        return sum;
    }
    
    public int getSumCantidad(){
        int rowCount = tablaVentas.getRowCount();
        int sum = 0;
        for(int i=0;i < rowCount;i++){
            sum=sum+Integer.parseInt(tablaVentas.getValueAt(i, 0).toString());
        }
        return sum;
    }
    
    class horas implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Date sistHora=new Date();
            String pmAm="hh:mm:ss a";
            SimpleDateFormat format=new SimpleDateFormat(pmAm);
            Calendar hoy=Calendar.getInstance();
            txtHora.setText(String.format(format.format(sistHora),hoy));
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroupTipo = new javax.swing.ButtonGroup();
        panelCategoria = new javax.swing.JPanel();
        btnCafe = new javax.swing.JButton();
        btnChocolate = new javax.swing.JButton();
        btnInfusion = new javax.swing.JButton();
        btnZumo = new javax.swing.JButton();
        btnCroissant = new javax.swing.JButton();
        btnCookie = new javax.swing.JButton();
        btnMenus = new javax.swing.JButton();
        btnMadalena = new javax.swing.JButton();
        btnBocadillos = new javax.swing.JButton();
        panelTablaVentas = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        panelNumerico = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnDescuento = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnCobrar = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnAcceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTotalNeto = new javax.swing.JTextField();
        panelDisplay = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtIDCliente = new javax.swing.JTextField();
        btnResetIDCliente = new javax.swing.JButton();
        txtCantidad = new javax.swing.JTextField();
        panelCardTipo = new javax.swing.JPanel();
        pnlCafe = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        panelChocolate = new javax.swing.JPanel();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        panelInfusiones = new javax.swing.JPanel();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jToggleButton23 = new javax.swing.JToggleButton();
        jToggleButton25 = new javax.swing.JToggleButton();
        jToggleButton24 = new javax.swing.JToggleButton();
        jToggleButton26 = new javax.swing.JToggleButton();
        jToggleButton27 = new javax.swing.JToggleButton();
        panelZumos = new javax.swing.JPanel();
        jToggleButton28 = new javax.swing.JToggleButton();
        jToggleButton29 = new javax.swing.JToggleButton();
        jToggleButton30 = new javax.swing.JToggleButton();
        jToggleButton31 = new javax.swing.JToggleButton();
        jToggleButton34 = new javax.swing.JToggleButton();
        jToggleButton32 = new javax.swing.JToggleButton();
        jToggleButton33 = new javax.swing.JToggleButton();
        jToggleButton35 = new javax.swing.JToggleButton();
        jToggleButton36 = new javax.swing.JToggleButton();
        panelBolleria = new javax.swing.JPanel();
        jToggleButton37 = new javax.swing.JToggleButton();
        jToggleButton38 = new javax.swing.JToggleButton();
        jToggleButton39 = new javax.swing.JToggleButton();
        jToggleButton40 = new javax.swing.JToggleButton();
        jToggleButton41 = new javax.swing.JToggleButton();
        jToggleButton42 = new javax.swing.JToggleButton();
        jToggleButton43 = new javax.swing.JToggleButton();
        jToggleButton44 = new javax.swing.JToggleButton();
        jToggleButton45 = new javax.swing.JToggleButton();
        panelCookies = new javax.swing.JPanel();
        jToggleButton46 = new javax.swing.JToggleButton();
        jToggleButton47 = new javax.swing.JToggleButton();
        jToggleButton49 = new javax.swing.JToggleButton();
        jToggleButton48 = new javax.swing.JToggleButton();
        jToggleButton50 = new javax.swing.JToggleButton();
        jToggleButton51 = new javax.swing.JToggleButton();
        jToggleButton52 = new javax.swing.JToggleButton();
        jToggleButton53 = new javax.swing.JToggleButton();
        jToggleButton54 = new javax.swing.JToggleButton();
        panelMenus = new javax.swing.JPanel();
        jToggleButton55 = new javax.swing.JToggleButton();
        jToggleButton56 = new javax.swing.JToggleButton();
        jToggleButton57 = new javax.swing.JToggleButton();
        jToggleButton58 = new javax.swing.JToggleButton();
        jToggleButton59 = new javax.swing.JToggleButton();
        jToggleButton61 = new javax.swing.JToggleButton();
        jToggleButton60 = new javax.swing.JToggleButton();
        jToggleButton62 = new javax.swing.JToggleButton();
        jToggleButton63 = new javax.swing.JToggleButton();
        panelMadalenas = new javax.swing.JPanel();
        jToggleButton64 = new javax.swing.JToggleButton();
        jToggleButton65 = new javax.swing.JToggleButton();
        jToggleButton66 = new javax.swing.JToggleButton();
        jToggleButton67 = new javax.swing.JToggleButton();
        jToggleButton68 = new javax.swing.JToggleButton();
        jToggleButton69 = new javax.swing.JToggleButton();
        jToggleButton70 = new javax.swing.JToggleButton();
        jToggleButton71 = new javax.swing.JToggleButton();
        jToggleButton72 = new javax.swing.JToggleButton();
        panelBocadillos = new javax.swing.JPanel();
        jToggleButton73 = new javax.swing.JToggleButton();
        jToggleButton74 = new javax.swing.JToggleButton();
        jToggleButton75 = new javax.swing.JToggleButton();
        jToggleButton76 = new javax.swing.JToggleButton();
        jToggleButton77 = new javax.swing.JToggleButton();
        jToggleButton79 = new javax.swing.JToggleButton();
        jToggleButton78 = new javax.swing.JToggleButton();
        jToggleButton80 = new javax.swing.JToggleButton();
        jToggleButton81 = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTotalBruto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(900, 800));

        panelCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categoria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 0, 204))); // NOI18N
        panelCategoria.setLayout(new java.awt.GridLayout(0, 3));

        btnCafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/hauptman/imagenes/Coffee-icon.png"))); // NOI18N
        btnCafe.setText("Cafés");
        btnCafe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCafe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCafeActionPerformed(evt);
            }
        });
        panelCategoria.add(btnCafe);

        btnChocolate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/hauptman/imagenes/Hot-Chocolate-icon.png"))); // NOI18N
        btnChocolate.setText("Chocolates");
        btnChocolate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChocolate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChocolateActionPerformed(evt);
            }
        });
        panelCategoria.add(btnChocolate);

        btnInfusion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/hauptman/imagenes/Cup-2-tea-hot-icon.png"))); // NOI18N
        btnInfusion.setText("Infusiones");
        btnInfusion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInfusion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInfusion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfusionActionPerformed(evt);
            }
        });
        panelCategoria.add(btnInfusion);

        btnZumo.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        btnZumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/hauptman/imagenes/icons8-orange-juice-40.png"))); // NOI18N
        btnZumo.setText("Zumos");
        btnZumo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnZumo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnZumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZumoActionPerformed(evt);
            }
        });
        panelCategoria.add(btnZumo);

        btnCroissant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/hauptman/imagenes/Croissant-icon.png"))); // NOI18N
        btnCroissant.setText("Bollería");
        btnCroissant.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCroissant.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCroissant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCroissantActionPerformed(evt);
            }
        });
        panelCategoria.add(btnCroissant);

        btnCookie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/hauptman/imagenes/Apps-preferences-web-browser-cookies-icon.png"))); // NOI18N
        btnCookie.setText("Cookie");
        btnCookie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCookie.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCookie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCookieActionPerformed(evt);
            }
        });
        panelCategoria.add(btnCookie);

        btnMenus.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        btnMenus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/hauptman/imagenes/Breakfast-icon.png"))); // NOI18N
        btnMenus.setText("Menús");
        btnMenus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenus.setName(""); // NOI18N
        btnMenus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenusActionPerformed(evt);
            }
        });
        panelCategoria.add(btnMenus);

        btnMadalena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/hauptman/imagenes/muffin-icon.png"))); // NOI18N
        btnMadalena.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMadalena.setLabel("Madalenas");
        btnMadalena.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMadalena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMadalenaActionPerformed(evt);
            }
        });
        panelCategoria.add(btnMadalena);

        btnBocadillos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/hauptman/imagenes/icons8-hot-dog-40.png"))); // NOI18N
        btnBocadillos.setText("Bocadillos");
        btnBocadillos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBocadillos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBocadillos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBocadillosActionPerformed(evt);
            }
        });
        panelCategoria.add(btnBocadillos);

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cant.", "Descripción", "Dto.", "Precio", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        panelTablaVentas.setViewportView(tablaVentas);
        if (tablaVentas.getColumnModel().getColumnCount() > 0) {
            tablaVentas.getColumnModel().getColumn(2).setHeaderValue("Dto.");
        }

        panelNumerico.setLayout(new java.awt.GridLayout(4, 4));

        btn1.setText("1");
        btn1.setName("1"); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });
        panelNumerico.add(btn1);

        btn2.setText("2");
        btn2.setName("2"); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });
        panelNumerico.add(btn2);

        btn3.setText("3");
        btn3.setName("3"); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });
        panelNumerico.add(btn3);

        btnDescuento.setText("%Dto.");
        btnDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescuentoActionPerformed(evt);
            }
        });
        panelNumerico.add(btnDescuento);

        btn4.setText("4");
        btn4.setName("4"); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });
        panelNumerico.add(btn4);

        btn5.setText("5");
        btn5.setName("5"); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });
        panelNumerico.add(btn5);

        btn6.setText("6");
        btn6.setName("6"); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });
        panelNumerico.add(btn6);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panelNumerico.add(btnEliminar);

        btn7.setText("7");
        btn7.setName("7"); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });
        panelNumerico.add(btn7);

        btn8.setText("8");
        btn8.setName("8"); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });
        panelNumerico.add(btn8);

        btn9.setText("9");
        btn9.setName("9"); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });
        panelNumerico.add(btn9);

        btnCobrar.setText("Cobrar");
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });
        panelNumerico.add(btnCobrar);

        btn0.setText("0");
        btn0.setName("0"); // NOI18N
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });
        panelNumerico.add(btn0);

        btnPunto.setText(".");
        btnPunto.setName("."); // NOI18N
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });
        panelNumerico.add(btnPunto);

        btnClear.setText("C");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        panelNumerico.add(btnClear);

        btnAcceptar.setText("Acceptar");
        btnAcceptar.setOpaque(true);
        btnAcceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptarActionPerformed(evt);
            }
        });
        panelNumerico.add(btnAcceptar);

        jLabel1.setText("Total:");

        txtTotalNeto.setEditable(false);
        txtTotalNeto.setBackground(new java.awt.Color(51, 102, 255));
        txtTotalNeto.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        txtTotalNeto.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalNeto.setOpaque(true);

        lblFecha.setText("Fecha:");

        txtFecha.setEditable(false);

        jLabel2.setText("Hora:");

        txtHora.setEditable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel3.setText("ID Cliente:");

        txtIDCliente.setEditable(false);

        btnResetIDCliente.setText("Reset");
        btnResetIDCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetIDClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResetIDCliente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetIDCliente))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelDisplayLayout = new javax.swing.GroupLayout(panelDisplay);
        panelDisplay.setLayout(panelDisplayLayout);
        panelDisplayLayout.setHorizontalGroup(
            panelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDisplayLayout.createSequentialGroup()
                        .addComponent(lblFecha)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel2))
                    .addGroup(panelDisplayLayout.createSequentialGroup()
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelDisplayLayout.setVerticalGroup(
            panelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDisplayLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(panelDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        txtCantidad.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        txtCantidad.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCantidad.setOpaque(true);

        panelCardTipo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 0, 204))); // NOI18N
        panelCardTipo.setLayout(new java.awt.CardLayout());

        pnlCafe.setLayout(new java.awt.GridLayout(3, 3));

        buttonGroupTipo.add(jToggleButton1);
        jToggleButton1.setText("Café Largo");
        jToggleButton1.setName("cafe largo"); // NOI18N
        jToggleButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        pnlCafe.add(jToggleButton1);

        buttonGroupTipo.add(jToggleButton2);
        jToggleButton2.setText("Café Corto");
        jToggleButton2.setName("cafe corto"); // NOI18N
        jToggleButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        pnlCafe.add(jToggleButton2);

        buttonGroupTipo.add(jToggleButton3);
        jToggleButton3.setText("Cortado");
        jToggleButton3.setName("cafe cortado"); // NOI18N
        jToggleButton3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        pnlCafe.add(jToggleButton3);

        buttonGroupTipo.add(jToggleButton4);
        jToggleButton4.setText("Café con Leche");
        jToggleButton4.setName("cafe con leche"); // NOI18N
        jToggleButton4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        pnlCafe.add(jToggleButton4);

        buttonGroupTipo.add(jToggleButton5);
        jToggleButton5.setText("Capuccino");
        jToggleButton5.setName("capuccino"); // NOI18N
        jToggleButton5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        pnlCafe.add(jToggleButton5);

        buttonGroupTipo.add(jToggleButton6);
        jToggleButton6.setText("Carajillo");
        jToggleButton6.setName("carajillo"); // NOI18N
        jToggleButton6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        pnlCafe.add(jToggleButton6);

        buttonGroupTipo.add(jToggleButton7);
        pnlCafe.add(jToggleButton7);

        buttonGroupTipo.add(jToggleButton8);
        pnlCafe.add(jToggleButton8);

        buttonGroupTipo.add(jToggleButton9);
        pnlCafe.add(jToggleButton9);

        panelCardTipo.add(pnlCafe, "cafe");

        panelChocolate.setLayout(new java.awt.GridLayout(3, 3));

        buttonGroupTipo.add(jToggleButton10);
        jToggleButton10.setText("Chocolate Suizo");
        jToggleButton10.setName("chocolate suizo"); // NOI18N
        jToggleButton10.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelChocolate.add(jToggleButton10);

        buttonGroupTipo.add(jToggleButton11);
        jToggleButton11.setText("Taza Grande");
        jToggleButton11.setName("chocolate taza grande"); // NOI18N
        jToggleButton11.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelChocolate.add(jToggleButton11);

        buttonGroupTipo.add(jToggleButton13);
        jToggleButton13.setText("Taza Pequeña");
        jToggleButton13.setName("chocolate taza pequena"); // NOI18N
        jToggleButton13.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelChocolate.add(jToggleButton13);

        buttonGroupTipo.add(jToggleButton12);
        panelChocolate.add(jToggleButton12);

        buttonGroupTipo.add(jToggleButton14);
        panelChocolate.add(jToggleButton14);

        buttonGroupTipo.add(jToggleButton15);
        panelChocolate.add(jToggleButton15);

        buttonGroupTipo.add(jToggleButton16);
        panelChocolate.add(jToggleButton16);

        buttonGroupTipo.add(jToggleButton17);
        panelChocolate.add(jToggleButton17);

        buttonGroupTipo.add(jToggleButton18);
        panelChocolate.add(jToggleButton18);

        panelCardTipo.add(panelChocolate, "chocolate");

        panelInfusiones.setLayout(new java.awt.GridLayout(3, 3));

        buttonGroupTipo.add(jToggleButton19);
        jToggleButton19.setText("Té Negro");
        jToggleButton19.setName("te negro"); // NOI18N
        jToggleButton19.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelInfusiones.add(jToggleButton19);

        buttonGroupTipo.add(jToggleButton20);
        jToggleButton20.setText("Té con Leche");
        jToggleButton20.setName("te con leche"); // NOI18N
        jToggleButton20.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelInfusiones.add(jToggleButton20);

        buttonGroupTipo.add(jToggleButton22);
        jToggleButton22.setText("Chai Latte");
        jToggleButton22.setName("chai latte"); // NOI18N
        jToggleButton22.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelInfusiones.add(jToggleButton22);

        buttonGroupTipo.add(jToggleButton21);
        jToggleButton21.setText("Menta");
        jToggleButton21.setName("menta"); // NOI18N
        jToggleButton21.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelInfusiones.add(jToggleButton21);

        buttonGroupTipo.add(jToggleButton23);
        jToggleButton23.setText("Manzanilla");
        jToggleButton23.setName("manzanilla"); // NOI18N
        jToggleButton23.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelInfusiones.add(jToggleButton23);

        buttonGroupTipo.add(jToggleButton25);
        panelInfusiones.add(jToggleButton25);

        buttonGroupTipo.add(jToggleButton24);
        panelInfusiones.add(jToggleButton24);

        buttonGroupTipo.add(jToggleButton26);
        panelInfusiones.add(jToggleButton26);

        buttonGroupTipo.add(jToggleButton27);
        panelInfusiones.add(jToggleButton27);

        panelCardTipo.add(panelInfusiones, "infusiones");

        panelZumos.setLayout(new java.awt.GridLayout(3, 3));

        buttonGroupTipo.add(jToggleButton28);
        jToggleButton28.setText("Naranja Natural");
        jToggleButton28.setName("naranja natural"); // NOI18N
        jToggleButton28.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelZumos.add(jToggleButton28);

        buttonGroupTipo.add(jToggleButton29);
        jToggleButton29.setText("Piña");
        jToggleButton29.setName("pina"); // NOI18N
        jToggleButton29.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelZumos.add(jToggleButton29);

        buttonGroupTipo.add(jToggleButton30);
        jToggleButton30.setText("Melocotón");
        jToggleButton30.setName("melocoton"); // NOI18N
        jToggleButton30.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelZumos.add(jToggleButton30);

        buttonGroupTipo.add(jToggleButton31);
        panelZumos.add(jToggleButton31);

        buttonGroupTipo.add(jToggleButton34);
        panelZumos.add(jToggleButton34);

        buttonGroupTipo.add(jToggleButton32);
        panelZumos.add(jToggleButton32);

        buttonGroupTipo.add(jToggleButton33);
        panelZumos.add(jToggleButton33);

        buttonGroupTipo.add(jToggleButton35);
        panelZumos.add(jToggleButton35);

        buttonGroupTipo.add(jToggleButton36);
        panelZumos.add(jToggleButton36);

        panelCardTipo.add(panelZumos, "zumos");
        panelZumos.getAccessibleContext().setAccessibleName("");

        panelBolleria.setLayout(new java.awt.GridLayout(3, 3));

        buttonGroupTipo.add(jToggleButton37);
        jToggleButton37.setText("Croissant Normal");
        jToggleButton37.setName("croissant normal"); // NOI18N
        jToggleButton37.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelBolleria.add(jToggleButton37);

        buttonGroupTipo.add(jToggleButton38);
        jToggleButton38.setText("Croissant Integral");
        jToggleButton38.setName("croissant integral"); // NOI18N
        jToggleButton38.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelBolleria.add(jToggleButton38);

        buttonGroupTipo.add(jToggleButton39);
        jToggleButton39.setText("Croissant Chocolate");
        jToggleButton39.setName("croissant chocolate"); // NOI18N
        jToggleButton39.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelBolleria.add(jToggleButton39);

        buttonGroupTipo.add(jToggleButton40);
        jToggleButton40.setText("Brownie");
        jToggleButton40.setName("brownie"); // NOI18N
        jToggleButton40.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelBolleria.add(jToggleButton40);

        buttonGroupTipo.add(jToggleButton41);
        jToggleButton41.setText("Pastel Chocolate");
        jToggleButton41.setName("pastel de chocolate"); // NOI18N
        jToggleButton41.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelBolleria.add(jToggleButton41);

        buttonGroupTipo.add(jToggleButton42);
        jToggleButton42.setText("Tarta de Fresa");
        jToggleButton42.setName("tarta de fresa"); // NOI18N
        jToggleButton42.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelBolleria.add(jToggleButton42);

        buttonGroupTipo.add(jToggleButton43);
        panelBolleria.add(jToggleButton43);

        buttonGroupTipo.add(jToggleButton44);
        panelBolleria.add(jToggleButton44);

        buttonGroupTipo.add(jToggleButton45);
        panelBolleria.add(jToggleButton45);

        panelCardTipo.add(panelBolleria, "bolleria");

        panelCookies.setLayout(new java.awt.GridLayout(3, 3));

        buttonGroupTipo.add(jToggleButton46);
        jToggleButton46.setText("Chocolate Negro");
        jToggleButton46.setName("cookie de chocolate negro"); // NOI18N
        jToggleButton46.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelCookies.add(jToggleButton46);

        buttonGroupTipo.add(jToggleButton47);
        jToggleButton47.setText("Chocolate Blanco");
        jToggleButton47.setName("cookie de chocolate blanco"); // NOI18N
        jToggleButton47.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelCookies.add(jToggleButton47);

        buttonGroupTipo.add(jToggleButton49);
        jToggleButton49.setText("Caramelo");
        jToggleButton49.setName("cookie de caramelo"); // NOI18N
        jToggleButton49.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelCookies.add(jToggleButton49);

        buttonGroupTipo.add(jToggleButton48);
        panelCookies.add(jToggleButton48);

        buttonGroupTipo.add(jToggleButton50);
        panelCookies.add(jToggleButton50);

        buttonGroupTipo.add(jToggleButton51);
        panelCookies.add(jToggleButton51);

        buttonGroupTipo.add(jToggleButton52);
        panelCookies.add(jToggleButton52);

        buttonGroupTipo.add(jToggleButton53);
        panelCookies.add(jToggleButton53);

        buttonGroupTipo.add(jToggleButton54);
        panelCookies.add(jToggleButton54);

        panelCardTipo.add(panelCookies, "cookies");

        panelMenus.setName(""); // NOI18N
        panelMenus.setLayout(new java.awt.GridLayout(3, 3));

        buttonGroupTipo.add(jToggleButton55);
        jToggleButton55.setText("Menu del dia");
        jToggleButton55.setName("menu del dia"); // NOI18N
        jToggleButton55.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelMenus.add(jToggleButton55);

        buttonGroupTipo.add(jToggleButton56);
        jToggleButton56.setText("Menu desayuno");
        jToggleButton56.setName("menu desayuno"); // NOI18N
        jToggleButton56.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelMenus.add(jToggleButton56);

        buttonGroupTipo.add(jToggleButton57);
        panelMenus.add(jToggleButton57);

        buttonGroupTipo.add(jToggleButton58);
        panelMenus.add(jToggleButton58);

        buttonGroupTipo.add(jToggleButton59);
        panelMenus.add(jToggleButton59);

        buttonGroupTipo.add(jToggleButton61);
        panelMenus.add(jToggleButton61);

        buttonGroupTipo.add(jToggleButton60);
        panelMenus.add(jToggleButton60);

        buttonGroupTipo.add(jToggleButton62);
        panelMenus.add(jToggleButton62);

        buttonGroupTipo.add(jToggleButton63);
        panelMenus.add(jToggleButton63);

        panelCardTipo.add(panelMenus, "menus");

        panelMadalenas.setLayout(new java.awt.GridLayout(3, 3));

        buttonGroupTipo.add(jToggleButton64);
        jToggleButton64.setText("Mini Madalena");
        jToggleButton64.setName("mini madalena"); // NOI18N
        jToggleButton64.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelMadalenas.add(jToggleButton64);

        buttonGroupTipo.add(jToggleButton65);
        jToggleButton65.setText("Madalena Integral");
        jToggleButton65.setName("madalena integral"); // NOI18N
        jToggleButton65.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelMadalenas.add(jToggleButton65);

        buttonGroupTipo.add(jToggleButton66);
        jToggleButton66.setText("Mad. de Chocolate");
        jToggleButton66.setName("madalena de chocolate"); // NOI18N
        jToggleButton66.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelMadalenas.add(jToggleButton66);

        buttonGroupTipo.add(jToggleButton67);
        jToggleButton67.setText("Mad. de Arandanos");
        jToggleButton67.setName("madalena de arandano"); // NOI18N
        jToggleButton67.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelMadalenas.add(jToggleButton67);

        buttonGroupTipo.add(jToggleButton68);
        panelMadalenas.add(jToggleButton68);

        buttonGroupTipo.add(jToggleButton69);
        panelMadalenas.add(jToggleButton69);

        buttonGroupTipo.add(jToggleButton70);
        panelMadalenas.add(jToggleButton70);

        buttonGroupTipo.add(jToggleButton71);
        panelMadalenas.add(jToggleButton71);

        buttonGroupTipo.add(jToggleButton72);
        panelMadalenas.add(jToggleButton72);

        panelCardTipo.add(panelMadalenas, "madalenas");

        panelBocadillos.setLayout(new java.awt.GridLayout(3, 3));

        buttonGroupTipo.add(jToggleButton73);
        jToggleButton73.setText("Bocadillo de Carne");
        jToggleButton73.setName("bocadillo carne"); // NOI18N
        jToggleButton73.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelBocadillos.add(jToggleButton73);

        buttonGroupTipo.add(jToggleButton74);
        jToggleButton74.setText("Bocadillo de Atún");
        jToggleButton74.setName("bocadillo atun"); // NOI18N
        jToggleButton74.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelBocadillos.add(jToggleButton74);

        buttonGroupTipo.add(jToggleButton75);
        jToggleButton75.setText("Bikini");
        jToggleButton75.setName("bikini"); // NOI18N
        jToggleButton75.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelBocadillos.add(jToggleButton75);

        buttonGroupTipo.add(jToggleButton76);
        jToggleButton76.setText("Bocadillo de Pollo");
        jToggleButton76.setName("bocadillo pollo"); // NOI18N
        jToggleButton76.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelBocadillos.add(jToggleButton76);

        buttonGroupTipo.add(jToggleButton77);
        jToggleButton77.setText("Jamón Serrano");
        jToggleButton77.setName("bocadillo jamon serrano"); // NOI18N
        jToggleButton77.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton1ItemStateChanged(evt);
            }
        });
        panelBocadillos.add(jToggleButton77);

        buttonGroupTipo.add(jToggleButton79);
        panelBocadillos.add(jToggleButton79);

        buttonGroupTipo.add(jToggleButton78);
        panelBocadillos.add(jToggleButton78);

        buttonGroupTipo.add(jToggleButton80);
        panelBocadillos.add(jToggleButton80);

        buttonGroupTipo.add(jToggleButton81);
        panelBocadillos.add(jToggleButton81);

        panelCardTipo.add(panelBocadillos, "bocadillos");

        jLabel5.setText("Cantidad:");

        jLabel6.setText("Subtotal:");

        txtTotalBruto.setEditable(false);
        txtTotalBruto.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtTotalBruto.setPreferredSize(new java.awt.Dimension(14, 28));

        jLabel8.setText("Descuento:");

        txtDesc.setEditable(false);
        txtDesc.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtTotalBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addComponent(jLabel8))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(64, 64, 64))
                            .addComponent(txtTotalNeto)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidad))
                    .addComponent(panelNumerico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTablaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCardTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 473, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelTablaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTotalBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addComponent(txtTotalNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelCardTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(13, 13, 13)
                        .addComponent(panelNumerico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        txtCantidad.setText(txtCantidad.getText() + 
                ((JButton)evt.getSource()).getName());
    }//GEN-LAST:event_btnCalcActionPerformed

    private void btnCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCafeActionPerformed
        CardLayout cl = (CardLayout) (panelCardTipo.getLayout());
        cl.show(panelCardTipo, "cafe");    
    }//GEN-LAST:event_btnCafeActionPerformed

    private void btnChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChocolateActionPerformed
        CardLayout cl = (CardLayout) (panelCardTipo.getLayout());
        cl.show(panelCardTipo, "chocolate");
    }//GEN-LAST:event_btnChocolateActionPerformed

    private void btnCroissantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCroissantActionPerformed
        CardLayout cl = (CardLayout) (panelCardTipo.getLayout());
        cl.show(panelCardTipo, "bolleria");
    }//GEN-LAST:event_btnCroissantActionPerformed

    private void btnInfusionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfusionActionPerformed
        CardLayout cl = (CardLayout) (panelCardTipo.getLayout());
        cl.show(panelCardTipo, "infusiones");
    }//GEN-LAST:event_btnInfusionActionPerformed

    private void btnZumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZumoActionPerformed
        CardLayout cl = (CardLayout) (panelCardTipo.getLayout());
        cl.show(panelCardTipo, "zumos");
    }//GEN-LAST:event_btnZumoActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
       txtCantidad.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAcceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptarActionPerformed
        
        if (!txtCantidad.getText().equals("")) {
            //FIXME cantidad comprada para um mismo producto várias veces.
            prodSeleccionado.setCantidadComprada(Integer.parseInt(txtCantidad.getText()));
            int cantidadInicial = prodSeleccionado.getCantidadStock();
            int cantidad = prodSeleccionado.getCantidadStock() - prodSeleccionado.getCantidadComprada();
            
            if(cantidadInicial == 0){
                JOptionPane.showMessageDialog(this, "El producto: " 
                        + prodSeleccionado.getDescripcion() + " se ha terminado.");
                
            }else if(cantidadInicial > 0 & cantidad >= 0){
                listaProductosVenta.add(prodSeleccionado);
                DefaultTableModel model = (DefaultTableModel) tablaVentas.getModel();
                model.addRow(prodSeleccionado.getRow());
                
            }else if (cantidad < 0){
                JOptionPane.showMessageDialog(this, "No hay esta cantidad de: " 
                        + prodSeleccionado.getDescripcion().toUpperCase()
                        + "\nHay "+prodSeleccionado.getCantidadStock() 
                        + " " + prodSeleccionado.getDescripcion() + ".");
            } 

            //Pone la suma del subtotal en el campo Total.
            totalBruto = getSumPrecio();
            //NumberFormat currencyFormatter = NumberFormat.getCurrencyInstance(Locale.GERMANY);
            txtTotalBruto.setText(currencyFormatter.format(totalBruto));
            
            if(!txtDesc.getText().equals("") && !txtDesc.getText().equals("0")){
                actualizaDescuento(currencyFormatter);
            }else if (txtDesc.getText().equals("") || txtDesc.getText().equals("0")){
                txtTotalNeto.setText(currencyFormatter.format(totalBruto));
            }

            buttonGroupTipo.clearSelection();
            txtCantidad.setText("");
        
        }else {
            JOptionPane.showMessageDialog(this, "Seleccione una cantidad y pulse el botón Acceptar");
        }    
    }//GEN-LAST:event_btnAcceptarActionPerformed

    private void jToggleButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jToggleButton1ItemStateChanged
        
        DefaultTableModel model = (DefaultTableModel) tablaVentas.getModel();
        
        if(evt.getStateChange() == ItemEvent.SELECTED){
            //Productos prodSeleccionado = new Productos();
            prodSeleccionado = accionesVentas.getProductosVenta().
                    get(((JToggleButton)evt.getItem()).getName());
            btnAcceptar.setBackground(Color.GREEN);
            txtCantidad.setText("");
            //FIXME
            System.out.println(prodSeleccionado.getCantidadComprada());
        }
    }//GEN-LAST:event_jToggleButton1ItemStateChanged

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        DefaultTableModel model = (DefaultTableModel) tablaVentas.getModel();
        
        if (tablaVentas.getSelectedRow() != -1) {
            
            model.removeRow(tablaVentas.getSelectedRow());
            //NumberFormat currencyFormatter = NumberFormat.getCurrencyInstance();
            totalBruto = getSumPrecio();
            txtTotalBruto.setText(currencyFormatter.format(totalBruto));
            
            if(!txtDesc.getText().equals("") && !txtDesc.getText().equals("0")){
                actualizaDescuento(currencyFormatter);
            }else if (txtDesc.getText().equals("") || txtDesc.getText().equals("0")){
                totalBruto = getSumPrecio();
                txtTotalNeto.setText(currencyFormatter.format(totalBruto));
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void actualizaDescuento(NumberFormat currencyFormatter) throws NumberFormatException {
        double descuento = Double.parseDouble(txtDesc.getText());
        double porCien = totalBruto*(descuento/100);
        double actualizaDescuento = totalBruto - porCien;
        txtTotalNeto.setText(currencyFormatter.format(actualizaDescuento));
    }

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed

         DefaultTableModel model = (DefaultTableModel) tablaVentas.getModel();
         
         if(model.getRowCount() != 0 && model.getColumnCount() != 0){
         accionesFacturas.guardarDetalleFactura();
         accionesProductos.updateQdtVenta();
         //Limpia el ArrayList para la proxima venta.
         listaProductosVenta.clear();
         
         model.setNumRows(0);
         //NumberFormat currencyFormatter = NumberFormat.getCurrencyInstance();
         txtTotalNeto.setText(currencyFormatter.format(getSumPrecio()));
         txtTotalBruto.setText(currencyFormatter.format(getSumPrecio()));
         
         DialogFactura dialog = new DialogFactura(frame, true);
         dialog.setLocationRelativeTo(this);
         dialog.setVisible(true);
         } else{
             JOptionPane.showMessageDialog(this, "Seleccione un Producto.");
         }
             
    }//GEN-LAST:event_btnCobrarActionPerformed

    private void btnCookieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCookieActionPerformed
         CardLayout cl = (CardLayout) (panelCardTipo.getLayout());
         cl.show(panelCardTipo, "cookies"); 
    }//GEN-LAST:event_btnCookieActionPerformed

    private void btnMenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenusActionPerformed
        CardLayout cl = (CardLayout) (panelCardTipo.getLayout());
         cl.show(panelCardTipo, "menus"); 
    }//GEN-LAST:event_btnMenusActionPerformed

    private void btnMadalenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMadalenaActionPerformed
        CardLayout cl = (CardLayout) (panelCardTipo.getLayout());
         cl.show(panelCardTipo, "madalenas"); 
    }//GEN-LAST:event_btnMadalenaActionPerformed

    private void btnBocadillosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBocadillosActionPerformed
        CardLayout cl = (CardLayout) (panelCardTipo.getLayout());
         cl.show(panelCardTipo, "bocadillos"); 
    }//GEN-LAST:event_btnBocadillosActionPerformed

    private void btnDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescuentoActionPerformed
        // TODO add your handling code here:
         DialogDescuento dialogDescuento = new DialogDescuento(this);
         dialogDescuento.getTxtPrecio().setText(currencyFormatter.format(getSumPrecio()));
         dialogDescuento.setLocationRelativeTo(this);
         dialogDescuento.setVisible(true);
         
    }//GEN-LAST:event_btnDescuentoActionPerformed

    private void btnResetIDClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetIDClienteActionPerformed
        // TODO add your handling code here:
        txtIDCliente.setText("");
        txtDesc.setText("");
    }//GEN-LAST:event_btnResetIDClienteActionPerformed

    
// <editor-fold defaultstate="collapsed" desc="Getters and Setters">
    public JScrollPane getPanelTablaVentas() {
        return panelTablaVentas;
    }

    public JTable getTablaVentas() {
        return tablaVentas;
    } //</editor-fold>  
    
     //FIXME
    public Productos getProdSeleccionado() {
        return prodSeleccionado;
    }

    public JTextField getTxtFecha() {
        return txtFecha;
    }

    public JTextField getTxtHora() {
        return txtHora;
    }

    public JTextField getTxtTotalNeto() {
        return txtTotalNeto;
    }

    public JTextField getTxtTotalBruto() {
        return txtTotalBruto;
    }

    public List<Productos> getListaProductosVenta() {
        return listaProductosVenta;
    }

    public JTextField getTxtIDCliente() {
        return txtIDCliente;
    }

    public JTextField getTxtDesc() {
        return txtDesc;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAcceptar;
    private javax.swing.JButton btnBocadillos;
    private javax.swing.JButton btnCafe;
    private javax.swing.JButton btnChocolate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnCookie;
    private javax.swing.JButton btnCroissant;
    private javax.swing.JButton btnDescuento;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInfusion;
    private javax.swing.JButton btnMadalena;
    private javax.swing.JButton btnMenus;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnResetIDCliente;
    private javax.swing.JButton btnZumo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroupTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton26;
    private javax.swing.JToggleButton jToggleButton27;
    private javax.swing.JToggleButton jToggleButton28;
    private javax.swing.JToggleButton jToggleButton29;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton30;
    private javax.swing.JToggleButton jToggleButton31;
    private javax.swing.JToggleButton jToggleButton32;
    private javax.swing.JToggleButton jToggleButton33;
    private javax.swing.JToggleButton jToggleButton34;
    private javax.swing.JToggleButton jToggleButton35;
    private javax.swing.JToggleButton jToggleButton36;
    private javax.swing.JToggleButton jToggleButton37;
    private javax.swing.JToggleButton jToggleButton38;
    private javax.swing.JToggleButton jToggleButton39;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton40;
    private javax.swing.JToggleButton jToggleButton41;
    private javax.swing.JToggleButton jToggleButton42;
    private javax.swing.JToggleButton jToggleButton43;
    private javax.swing.JToggleButton jToggleButton44;
    private javax.swing.JToggleButton jToggleButton45;
    private javax.swing.JToggleButton jToggleButton46;
    private javax.swing.JToggleButton jToggleButton47;
    private javax.swing.JToggleButton jToggleButton48;
    private javax.swing.JToggleButton jToggleButton49;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton50;
    private javax.swing.JToggleButton jToggleButton51;
    private javax.swing.JToggleButton jToggleButton52;
    private javax.swing.JToggleButton jToggleButton53;
    private javax.swing.JToggleButton jToggleButton54;
    private javax.swing.JToggleButton jToggleButton55;
    private javax.swing.JToggleButton jToggleButton56;
    private javax.swing.JToggleButton jToggleButton57;
    private javax.swing.JToggleButton jToggleButton58;
    private javax.swing.JToggleButton jToggleButton59;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton60;
    private javax.swing.JToggleButton jToggleButton61;
    private javax.swing.JToggleButton jToggleButton62;
    private javax.swing.JToggleButton jToggleButton63;
    private javax.swing.JToggleButton jToggleButton64;
    private javax.swing.JToggleButton jToggleButton65;
    private javax.swing.JToggleButton jToggleButton66;
    private javax.swing.JToggleButton jToggleButton67;
    private javax.swing.JToggleButton jToggleButton68;
    private javax.swing.JToggleButton jToggleButton69;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton70;
    private javax.swing.JToggleButton jToggleButton71;
    private javax.swing.JToggleButton jToggleButton72;
    private javax.swing.JToggleButton jToggleButton73;
    private javax.swing.JToggleButton jToggleButton74;
    private javax.swing.JToggleButton jToggleButton75;
    private javax.swing.JToggleButton jToggleButton76;
    private javax.swing.JToggleButton jToggleButton77;
    private javax.swing.JToggleButton jToggleButton78;
    private javax.swing.JToggleButton jToggleButton79;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton80;
    private javax.swing.JToggleButton jToggleButton81;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JPanel panelBocadillos;
    private javax.swing.JPanel panelBolleria;
    private javax.swing.JPanel panelCardTipo;
    private javax.swing.JPanel panelCategoria;
    private javax.swing.JPanel panelChocolate;
    private javax.swing.JPanel panelCookies;
    private javax.swing.JPanel panelDisplay;
    private javax.swing.JPanel panelInfusiones;
    private javax.swing.JPanel panelMadalenas;
    private javax.swing.JPanel panelMenus;
    private javax.swing.JPanel panelNumerico;
    private javax.swing.JScrollPane panelTablaVentas;
    private javax.swing.JPanel panelZumos;
    private javax.swing.JPanel pnlCafe;
    private javax.swing.JTable tablaVentas;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtIDCliente;
    private javax.swing.JTextField txtTotalBruto;
    private javax.swing.JTextField txtTotalNeto;
    // End of variables declaration//GEN-END:variables
}
