/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.hauptman.vista;

import es.hauptman.acciones.AccionesCategorias;
import es.hauptman.acciones.AccionesProductos;
import es.hauptman.entities.Categorias;
import es.hauptman.principal.FrameHome;
import java.awt.event.ItemEvent;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 * Clase del panel que gestiona los productos.
 * @author Diego
 */
public class PanelProductos extends javax.swing.JPanel {
    private FrameHome frame;
    private AccionesProductos accionesProductos = new AccionesProductos(this);
    private AccionesCategorias accionesCategorias;
    private DefaultTableModel model;
    /**
     * Creates new form PanelProductos
     * @param frame
     */
    public PanelProductos(FrameHome frame) {
        this.frame = frame;
        initComponents();
        model = (DefaultTableModel) tablaProductos.getModel();
        model.setNumRows(0);
        accionesCategorias = new AccionesCategorias(this);
        disableComponents();
        accionesCategorias.readCboAccionesCategorias();
        MyIntFilter.formatInt(txtIdCat);
        MyIntFilter.formatInt(txtCtd);
        MyIntFilter.formatInt(txtIdProd);
        MyDoubleFilter.formatDouble(txtPrecio);
        
    }
    
// <editor-fold defaultstate="collapsed" desc="Getters and Setters">
    public JTable getTablaProductos() {
        return tablaProductos;
    }

    public JTextField getTxtCategoria() {
        return txtCategoria;
    }

    public JTextField getTxtCtd() {
        return txtCtd;
    }

    public JTextField getTxtIdCat() {
        return txtIdCat;
    }

    public JTextField getTxtIdProd() {
        return txtIdProd;
    }

    public JTextField getTxtPrecio() {
        return txtPrecio;
    }

    public JTextField getTxtProducto() {
        return txtProducto;
    }

    public JComboBox<Object> getCboCatProd() {
        return cboCatProd;
    }

    public JComboBox<Object> getCboSearchCat() {
        return cboSearchCat;
    }

    public JComboBox<Object> getCboSearchProd() {
        return cboSearchProd;
    }//</editor-fold> 
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        pnlCategorias = new javax.swing.JPanel();
        lblDescCat = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        lblCatId = new javax.swing.JLabel();
        txtIdCat = new javax.swing.JTextField();
        btnCrearCat = new javax.swing.JButton();
        btnActualizarCat = new javax.swing.JButton();
        btnEliminarCat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        btnLimpiaTabla = new javax.swing.JButton();
        btnListarCategorias = new javax.swing.JButton();
        btnListarProductos = new javax.swing.JButton();
        pnlProductos = new javax.swing.JPanel();
        lblProdId = new javax.swing.JLabel();
        lblDescProd = new javax.swing.JLabel();
        txtIdProd = new javax.swing.JTextField();
        txtProducto = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        txtCtd = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        lblCboCatProd = new javax.swing.JLabel();
        cboCatProd = new javax.swing.JComboBox<>();
        btnCrearProd = new javax.swing.JButton();
        btnActualizarProd = new javax.swing.JButton();
        btnEliminarProd = new javax.swing.JButton();
        pnlBuscar = new javax.swing.JPanel();
        rdoBuscarCat = new javax.swing.JRadioButton();
        cboSearchCat = new javax.swing.JComboBox<>();
        cboSearchProd = new javax.swing.JComboBox<>();
        rdoBuscarProd = new javax.swing.JRadioButton();
        rdoCrearCat = new javax.swing.JRadioButton();
        rdoCrearProd = new javax.swing.JRadioButton();

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Cat", "Categoria", "ID Prod", "Poducto", "Cant. en Stock", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaProductosMousePressed(evt);
            }
        });
        tablaProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaProductosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProductos);

        pnlCategorias.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categorias", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N

        lblDescCat.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblDescCat.setText("Descripcíon:");

        txtCategoria.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        lblCatId.setText("ID Categoria:");

        btnCrearCat.setForeground(new java.awt.Color(0, 0, 204));
        btnCrearCat.setText("Crear");
        btnCrearCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCatActionPerformed(evt);
            }
        });

        btnActualizarCat.setForeground(new java.awt.Color(0, 0, 204));
        btnActualizarCat.setText("Actualizar");
        btnActualizarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarCatActionPerformed(evt);
            }
        });

        btnEliminarCat.setForeground(new java.awt.Color(0, 0, 204));
        btnEliminarCat.setText("Eliminar");
        btnEliminarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCategoriasLayout = new javax.swing.GroupLayout(pnlCategorias);
        pnlCategorias.setLayout(pnlCategoriasLayout);
        pnlCategoriasLayout.setHorizontalGroup(
            pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCategoriasLayout.createSequentialGroup()
                        .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCatId)
                            .addComponent(lblDescCat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdCat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlCategoriasLayout.createSequentialGroup()
                        .addComponent(btnCrearCat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizarCat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarCat)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCategoriasLayout.setVerticalGroup(
            pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCategoriasLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCatId)
                    .addComponent(txtIdCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescCat)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearCat)
                    .addComponent(btnActualizarCat)
                    .addComponent(btnEliminarCat))
                .addContainerGap())
        );

        btnLimpiar.setForeground(new java.awt.Color(0, 0, 204));
        btnLimpiar.setText("Limpiar Campos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnLimpiaTabla.setForeground(new java.awt.Color(0, 0, 204));
        btnLimpiaTabla.setText("Limpiar Tabla");
        btnLimpiaTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiaTablaActionPerformed(evt);
            }
        });

        btnListarCategorias.setForeground(new java.awt.Color(0, 0, 204));
        btnListarCategorias.setText("Todas las Categorias");
        btnListarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarCategoriasActionPerformed(evt);
            }
        });

        btnListarProductos.setForeground(new java.awt.Color(0, 0, 204));
        btnListarProductos.setText("Todos los productos");
        btnListarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnListarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnListarCategorias)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiaTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnLimpiaTabla)
                    .addComponent(btnListarCategorias)
                    .addComponent(btnListarProductos))
                .addContainerGap())
        );

        pnlProductos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N

        lblProdId.setText("ID Prod:");

        lblDescProd.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblDescProd.setText("Producto:");

        txtProducto.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        lblPrecio.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblPrecio.setText("Precio:");

        lblCantidad.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblCantidad.setText("Cantidad:");

        txtCtd.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        txtPrecio.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        lblCboCatProd.setText("Categoria:");

        cboCatProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Categoria>" }));
        cboCatProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCatProdActionPerformed(evt);
            }
        });

        btnCrearProd.setForeground(new java.awt.Color(0, 0, 204));
        btnCrearProd.setText("Crear");
        btnCrearProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProdActionPerformed(evt);
            }
        });

        btnActualizarProd.setForeground(new java.awt.Color(0, 0, 204));
        btnActualizarProd.setText("Actualizar");
        btnActualizarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarProdActionPerformed(evt);
            }
        });

        btnEliminarProd.setForeground(new java.awt.Color(0, 0, 204));
        btnEliminarProd.setText("Eliminar");
        btnEliminarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProductosLayout = new javax.swing.GroupLayout(pnlProductos);
        pnlProductos.setLayout(pnlProductosLayout);
        pnlProductosLayout.setHorizontalGroup(
            pnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductosLayout.createSequentialGroup()
                        .addComponent(btnCrearProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizarProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarProd)
                        .addGap(257, 257, 257))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductosLayout.createSequentialGroup()
                        .addGroup(pnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlProductosLayout.createSequentialGroup()
                                .addComponent(lblCboCatProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboCatProd, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlProductosLayout.createSequentialGroup()
                                .addGroup(pnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDescProd)
                                    .addComponent(lblPrecio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlProductosLayout.createSequentialGroup()
                                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(pnlProductosLayout.createSequentialGroup()
                                        .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlProductosLayout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(lblProdId)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlProductosLayout.createSequentialGroup()
                                                .addComponent(lblCantidad)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCtd)))))))
                        .addGap(205, 205, 205))))
        );
        pnlProductosLayout.setVerticalGroup(
            pnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductosLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(pnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCboCatProd)
                    .addComponent(cboCatProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProdId)
                    .addComponent(txtIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescProd)
                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidad)
                    .addComponent(txtCtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearProd)
                    .addComponent(btnActualizarProd)
                    .addComponent(btnEliminarProd))
                .addContainerGap())
        );

        pnlBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N

        buttonGroup1.add(rdoBuscarCat);
        rdoBuscarCat.setForeground(new java.awt.Color(0, 0, 204));
        rdoBuscarCat.setText("Categoria");
        rdoBuscarCat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdoBuscarCatItemStateChanged(evt);
            }
        });

        cboSearchCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Categoria>" }));
        cboSearchCat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboSearchCatItemStateChanged(evt);
            }
        });

        cboSearchProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Producto>" }));
        cboSearchProd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboSearchProdItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rdoBuscarProd);
        rdoBuscarProd.setForeground(new java.awt.Color(0, 0, 204));
        rdoBuscarProd.setText("Producto");
        rdoBuscarProd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdoBuscarProdItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlBuscarLayout = new javax.swing.GroupLayout(pnlBuscar);
        pnlBuscar.setLayout(pnlBuscarLayout);
        pnlBuscarLayout.setHorizontalGroup(
            pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboSearchProd, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoBuscarCat)
                    .addComponent(rdoBuscarProd)
                    .addComponent(cboSearchCat, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        pnlBuscarLayout.setVerticalGroup(
            pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdoBuscarCat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboSearchCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoBuscarProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cboSearchProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        buttonGroup1.add(rdoCrearCat);
        rdoCrearCat.setForeground(new java.awt.Color(0, 0, 204));
        rdoCrearCat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdoCrearCatItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rdoCrearProd);
        rdoCrearProd.setForeground(new java.awt.Color(0, 0, 204));
        rdoCrearProd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdoCrearProdItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdoCrearCat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoCrearProd)
                            .addComponent(pnlProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rdoCrearCat)
                            .addComponent(rdoCrearProd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(pnlBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProdActionPerformed
        if(cboCatProd.getSelectedIndex() == 0)
            {
                
            JOptionPane.showMessageDialog(frame, "Seleccione una Categoria.", 
                    "No se ha guardado.", JOptionPane.WARNING_MESSAGE);
            
        }else if (txtCtd.getText().equals("") 
                || txtPrecio.getText().equals("") 
                || txtProducto.getText().equals("")) {
            
            JOptionPane.showMessageDialog(frame, "Rellene todos los campos", 
                    "No se ha guardado.", JOptionPane.WARNING_MESSAGE);
            
        }else{
            accionesProductos.guardarProductos();
            model = (DefaultTableModel) tablaProductos.getModel();
            model.setNumRows(0);
            accionesProductos.getLastUpdatedProduct();
            limpiaCampos();
        }
    }//GEN-LAST:event_btnCrearProdActionPerformed

    private void btnEliminarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProdActionPerformed
        if(txtIdProd.getText().equals("")){
            
            JOptionPane.showMessageDialog(frame, "Seleccione un Producto o su ID.", 
                    "No se ha Eliminado", JOptionPane.WARNING_MESSAGE);
            
        }else{
        accionesProductos.eliminaProducto();
        DefaultTableModel model = (DefaultTableModel) 
                tablaProductos.getModel();
        model.removeRow(tablaProductos.getSelectedRow());
        limpiaCampos();
        }
    }//GEN-LAST:event_btnEliminarProdActionPerformed

    private void btnActualizarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarProdActionPerformed
        // TODO add your handling code here:
        if(txtIdProd.getText().equals("")){
            
            JOptionPane.showMessageDialog(frame, "Seleccione un Producto o su ID.", 
                    "No se ha modificado.", JOptionPane.WARNING_MESSAGE);
            
        }else if(txtCtd.getText().equals("") 
                || txtPrecio.getText().equals("") 
                || txtProducto.getText().equals("")){
            
            JOptionPane.showMessageDialog(frame, "Rellene todos los campos.", 
                    "No se ha actualizado", JOptionPane.WARNING_MESSAGE);
        
        }else{
        accionesProductos.editaProducto();
        //FIXME
        //accionesProductos.readListaProductos();
        model = (DefaultTableModel) tablaProductos.getModel();
        model.setNumRows(0);
        accionesProductos.getLastUpdatedProduct();
        limpiaCampos();
        }
    }//GEN-LAST:event_btnActualizarProdActionPerformed
    
    /**
     * Muestra las informaciones de las líneas de la tabla en los campos de texto. 
     * Hace una validacíon de los campos vacíos.
     * 
     */
    private void rowToTextField(){
        
        if (tablaProductos.getSelectedRow() != -1) {
            
            txtIdCat.setText(tablaProductos.getValueAt(tablaProductos.
                    getSelectedRow(), 0).toString());
            txtCategoria.setText(tablaProductos.getValueAt(tablaProductos.
                    getSelectedRow(), 1).toString());
            cboCatProd.getModel().setSelectedItem(tablaProductos.getValueAt(tablaProductos.
                    getSelectedRow(), 1));
            
            if(tablaProductos.getValueAt(tablaProductos.getSelectedRow(), 2) != null 
                    || tablaProductos.getValueAt(tablaProductos.getSelectedRow(), 3) != null
                    || tablaProductos.getValueAt(tablaProductos.getSelectedRow(), 4) != null
                    || tablaProductos.getValueAt(tablaProductos.getSelectedRow(), 5) != null)
            {
            txtIdProd.setText(tablaProductos.
                    getValueAt(tablaProductos.getSelectedRow(), 2).toString());
            txtProducto.setText(tablaProductos.
                    getValueAt(tablaProductos.getSelectedRow(), 3).toString());
            txtCtd.setText(tablaProductos.
                    getValueAt(tablaProductos.getSelectedRow(), 4).toString());
            txtPrecio.setText(tablaProductos.
                    getValueAt(tablaProductos.getSelectedRow(), 5).toString());
            }
        }
    }
    
    /**
     * Evento que muestra las informaciones de la tabla en los campos de texto 
     * al pulsar con el ratón.
     * @param evt 
     */
    private void tablaProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMousePressed
        rowToTextField();
    }//GEN-LAST:event_tablaProductosMousePressed
    /**
     * Evento que muestra las informaciones de la tabla en los campos de texto
     * al pulsar las flechas del teclado.
     * @param evt 
     */
    private void tablaProductosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaProductosKeyReleased
        rowToTextField();
    }//GEN-LAST:event_tablaProductosKeyReleased
    
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiaCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnListarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarProductosActionPerformed
        accionesProductos.readListaProductos();
    }//GEN-LAST:event_btnListarProductosActionPerformed

    private void cboSearchCatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboSearchCatItemStateChanged
        // TODO add your handling code here:
        if(cboSearchCat.getSelectedIndex() > 0)
            accionesProductos.readProdCatID();
    }//GEN-LAST:event_cboSearchCatItemStateChanged

    private void btnLimpiaTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiaTablaActionPerformed
        // TODO add your handling code here:
        model = (DefaultTableModel) tablaProductos.getModel();
        model.setNumRows(0);
    }//GEN-LAST:event_btnLimpiaTablaActionPerformed

    private void cboSearchProdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboSearchProdItemStateChanged
        // TODO add your handling code here:
        if(cboSearchProd.getSelectedIndex() > 0)
            accionesProductos.readAccionesProdByID();
        
    }//GEN-LAST:event_cboSearchProdItemStateChanged

    private void rdoBuscarCatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdoBuscarCatItemStateChanged
        // TODO add your handling code here:
        accionesCategorias.readCboAccionesCategorias();
        int state = evt.getStateChange();
        
        if(state == ItemEvent.SELECTED){
            pnlBuscar.setEnabled(true);
            cboSearchCat.setEnabled(true);
            limpiaCampos();
        } else if(state == ItemEvent.DESELECTED) {
            pnlBuscar.setEnabled(false);
            cboSearchCat.setEnabled(false);
        }
        
    }//GEN-LAST:event_rdoBuscarCatItemStateChanged

    private void rdoBuscarProdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdoBuscarProdItemStateChanged
        // TODO add your handling code here:
        accionesProductos.readProdCombo();
        int state = evt.getStateChange();
        
        if(state == ItemEvent.SELECTED){
            pnlBuscar.setEnabled(true);
            cboSearchProd.setEnabled(true);
            limpiaCampos();
        } else if(state == ItemEvent.DESELECTED) {
            pnlBuscar.setEnabled(false);
            cboSearchProd.setEnabled(false);
        }
        
    }//GEN-LAST:event_rdoBuscarProdItemStateChanged

    private void rdoCrearCatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdoCrearCatItemStateChanged

        int state = evt.getStateChange();
        
        if(state == ItemEvent.SELECTED){
            pnlCategorias.setEnabled(true);
            txtIdCat.setEnabled(true);
            txtCategoria.setEnabled(true);
            btnCrearCat.setEnabled(true);
            btnActualizarCat.setEnabled(true);
            btnEliminarCat.setEnabled(true);
            lblCatId.setEnabled(true);
            lblDescCat.setEnabled(true);
        }  else if (state == ItemEvent.DESELECTED) {
            pnlCategorias.setEnabled(false);
            txtIdCat.setEnabled(false);
            txtCategoria.setEnabled(false);
            btnCrearCat.setEnabled(false);
            btnActualizarCat.setEnabled(false);
            btnEliminarCat.setEnabled(false);
            lblCatId.setEnabled(false);
            lblDescCat.setEnabled(false);
            
        } 
        
    }//GEN-LAST:event_rdoCrearCatItemStateChanged

    private void rdoCrearProdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdoCrearProdItemStateChanged

        int state = evt.getStateChange();
        
        if(state == ItemEvent.SELECTED){
            pnlProductos.setEnabled(true);
            btnActualizarProd.setEnabled(true);
            btnEliminarProd.setEnabled(true);
            btnCrearProd.setEnabled(true);
            txtCtd.setEnabled(true);
            txtIdProd.setEnabled(true);
            txtProducto.setEnabled(true);
            txtPrecio.setEnabled(true);
            cboCatProd.setEnabled(true);
            lblCantidad.setEnabled(true);
            lblCboCatProd.setEnabled(true);
            lblDescProd.setEnabled(true);
            lblPrecio.setEnabled(true);
            lblProdId.setEnabled(true);
        }  else if (state == ItemEvent.DESELECTED){
            pnlProductos.setEnabled(false);
            btnActualizarProd.setEnabled(false);
            btnEliminarProd.setEnabled(false);
            btnCrearProd.setEnabled(false);
            txtCtd.setEnabled(false);
            txtIdProd.setEnabled(false);
            txtProducto.setEnabled(false);
            txtPrecio.setEnabled(false);
            cboCatProd.setEnabled(false);
            cboCatProd.setSelectedIndex(0);
            lblCantidad.setEnabled(false);
            lblCboCatProd.setEnabled(false);
            lblDescProd.setEnabled(false);
            lblPrecio.setEnabled(false);
            lblProdId.setEnabled(false);
        }  
        
        
    }//GEN-LAST:event_rdoCrearProdItemStateChanged

    private void btnCrearCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCatActionPerformed
        if(txtCategoria.getText().equals("")){
            JOptionPane.showMessageDialog(frame, "Rellene el campo 'Categoria'.", 
                    "No se ha creado la Categoria.", JOptionPane.WARNING_MESSAGE);
        }else{
        accionesCategorias.createAccionesCategorias();
        }
    }//GEN-LAST:event_btnCrearCatActionPerformed

    private void btnListarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarCategoriasActionPerformed
        accionesCategorias.readAllCategorias();
    }//GEN-LAST:event_btnListarCategoriasActionPerformed

    private void btnActualizarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCatActionPerformed
        if(txtIdCat.getText().equals("")){
            JOptionPane.showMessageDialog(frame, "Seleccione una Categoria o su ID.", 
                    "No se ha modificado la Categoria.", JOptionPane.WARNING_MESSAGE);
        }else{
        accionesCategorias.updateAccionesCategorias();
        }
    }//GEN-LAST:event_btnActualizarCatActionPerformed

    private void btnEliminarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCatActionPerformed
        if(txtIdCat.getText().equals("")){
            JOptionPane.showMessageDialog(frame, "Seleccione una Categoria o su ID.", 
                    "No se ha eliminado la Categoria.", JOptionPane.WARNING_MESSAGE);
        }else{
        accionesCategorias.deleteAccionesCategorias();
        model.removeRow(tablaProductos.getSelectedRow());
        limpiaCampos();
        }
    }//GEN-LAST:event_btnEliminarCatActionPerformed

    private void cboCatProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCatProdActionPerformed
        // TODO add your handling code here:
        if(cboCatProd.getSelectedItem() instanceof String == false){
            Categorias categoria = new Categorias();
            categoria = (Categorias) cboCatProd.getSelectedItem();
            if(categoria != null)
                txtIdCat.setText(String.valueOf(categoria.getID()));
        }
    }//GEN-LAST:event_cboCatProdActionPerformed
    /**
     * Método para desabilitar componentes.
     */
    private void disableComponents (){
            pnlBuscar.setEnabled(false);
            pnlCategorias.setEnabled(false);
            pnlProductos.setEnabled(false);
            
            btnActualizarProd.setEnabled(false);
            btnEliminarProd.setEnabled(false);
            btnCrearProd.setEnabled(false);
            txtCtd.setEnabled(false);
            txtIdProd.setEnabled(false);
            txtProducto.setEnabled(false);
            txtPrecio.setEnabled(false);
            
            txtIdCat.setEnabled(false);
            txtCategoria.setEnabled(false);
            btnCrearCat.setEnabled(false);
            btnActualizarCat.setEnabled(false);
            btnEliminarCat.setEnabled(false);
            
            cboSearchProd.setEnabled(false);
            cboSearchCat.setEnabled(false);
            cboCatProd.setEnabled(false);
    }
    /**
     * Método para limpiar campos de texto.
     */
    private void limpiaCampos(){
        
        txtIdCat.setText("");
        txtProducto.setText("");
        txtCtd.setText("");
        txtCategoria.setText("");
        txtIdCat.setText("");
        txtIdProd.setText("");
        txtPrecio.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarCat;
    private javax.swing.JButton btnActualizarProd;
    private javax.swing.JButton btnCrearCat;
    private javax.swing.JButton btnCrearProd;
    private javax.swing.JButton btnEliminarCat;
    private javax.swing.JButton btnEliminarProd;
    private javax.swing.JButton btnLimpiaTabla;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListarCategorias;
    private javax.swing.JButton btnListarProductos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<Object> cboCatProd;
    private javax.swing.JComboBox<Object> cboSearchCat;
    private javax.swing.JComboBox<Object> cboSearchProd;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCatId;
    private javax.swing.JLabel lblCboCatProd;
    private javax.swing.JLabel lblDescCat;
    private javax.swing.JLabel lblDescProd;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblProdId;
    private javax.swing.JPanel pnlBuscar;
    private javax.swing.JPanel pnlCategorias;
    private javax.swing.JPanel pnlProductos;
    private javax.swing.JRadioButton rdoBuscarCat;
    private javax.swing.JRadioButton rdoBuscarProd;
    private javax.swing.JRadioButton rdoCrearCat;
    private javax.swing.JRadioButton rdoCrearProd;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCtd;
    private javax.swing.JTextField txtIdCat;
    private javax.swing.JTextField txtIdProd;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables
}
